#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FAnimNode_Base.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::AnimGraphRuntime
{
    /**
     * ScriptStruct /Script/AnimGraphRuntime.AnimNode_MeshSpaceRefPose
     * Size -> 0x0000 (FullSize[0x0030] - InheritedSize[0x0030])
     */
    struct FAnimNode_MeshSpaceRefPose : public Engine::FAnimNode_Base
    {
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
