#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FPoseLink.h"
#include "Engine_FBoneReference.h"
#include "AnimGraphRuntime_ENUMS.h"
#include "CoreUObject_FVector.h"
#include "Engine_FInputScaleBias.h"
#include "Engine_FAnimNode_Base.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::AnimGraphRuntime
{
    /**
     * ScriptStruct /Script/AnimGraphRuntime.AnimNode_ScaleChainLength
     * Size -> 0x0080 (FullSize[0x00B0] - InheritedSize[0x0030])
     */
    struct FAnimNode_ScaleChainLength : public Engine::FAnimNode_Base
    {
    public:
        Engine::FPoseLink                                            InputPose;                                               //  Edit, NoDestructor, NativeAccessSpecifierPublic
        float                                                        DefaultChainLength;                                      //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::FBoneReference                                       ChainStartBone;                                          //  Edit, NoDestructor, NativeAccessSpecifierPublic
        Engine::FBoneReference                                       ChainEndBone;                                            //  Edit, NoDestructor, NativeAccessSpecifierPublic
        AnimGraphRuntime::EScaleChainInitialLength                   ChainInitialLength;                                      //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0001[0x3];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        CoreUObject::FVector                                         TargetLocation;                                          //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        Alpha;                                                   //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        float                                                        ActualAlpha;                                             //  ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        Engine::FInputScaleBias                                      AlphaScaleBias;                                          //  Edit, NoDestructor, NativeAccessSpecifierPublic
        bool                                                         bBoneIndicesCached;                                      //  ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0002[0x17];                                  //  MISSED OFFSET (PADDING)
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
