#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BaseballAIBatter_Blueprint_ABaseballAIBatter_Blueprint_C.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BaseballAIBatter_Easy_Blueprint
{
    /**
     * BlueprintGeneratedClass /Game/Blueprints/AI/Baseball/BaseballAIBatter_Easy_Blueprint.BaseballAIBatter_Easy_Blueprint_C
     * Size -> 0x0000 (FullSize[0x0ED2] - InheritedSize[0x0ED2])
     */
    class ABaseballAIBatter_Easy_Blueprint_C : public BaseballAIBatter_Blueprint::ABaseballAIBatter_Blueprint_C
    {
    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/Blueprints/AI/Baseball/BaseballAIBatter_Easy_Blueprint.BaseballAIBatter_Easy_Blueprint_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
