#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FPointerToUberGraphFrame.h"
#include "BasicTypes_TArray.h"
#include "Engine_AActor.h"
#include "Engine_ENUMS.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class USceneComponent; };
namespace CG::BaseballPracticeArenaWindow { class ABaseballPracticeArenaWindow_C; };
namespace CG::CoreUObject { class UClass; };
namespace CG::BaseballPracticeArenaLight { class ABaseballPracticeArenaLight_C; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BB_StadiumWindowSpawner
{
    /**
     * BlueprintGeneratedClass /Game/Blueprints/Targets/Baseball/BB_StadiumWindowSpawner.BB_StadiumWindowSpawner_C
     * Size -> 0x0040 (FullSize[0x0368] - InheritedSize[0x0328])
     */
    class ABB_StadiumWindowSpawner_C : public Engine::AActor
    {
    public:
        Engine::FPointerToUberGraphFrame                             UberGraphFrame;                                          //  ZeroConstructor, Transient, DuplicateTransient
        Engine::USceneComponent*                                     DefaultSceneRoot;                                        //  BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash
        BasicTypes::TArray<BaseballPracticeArenaWindow::ABaseballPracticeArenaWindow_C*> AllWindows;                                              //  Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance
        bool                                                         ShowTargetScore;                                         //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn
        uint8_t                                                      UnknownData_0000[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::AActor*                                              GameManager;                                             //  Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash
        BasicTypes::TArray<BaseballPracticeArenaLight::ABaseballPracticeArenaLight_C*> AllLightFixtures;                                        //  Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate

    public:
        void UserConstructionScript();
        void ActivateBreakables();
        void ResetBreakables();
        void CleanUpAllBreakables();
        void ReceiveEndPlay(Engine::EEndPlayReason EndPlayReason);
        void SetBreakableScore(int32_t WindowScore, int32_t LightFixtureScore);
        void ExecuteUbergraph_BB_StadiumWindowSpawner(int32_t EntryPoint);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/Blueprints/Targets/Baseball/BB_StadiumWindowSpawner.BB_StadiumWindowSpawner_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
