#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "CMN_Trail_Base_ACMN_Trail_Base_C.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BB_Trail_Normal_Flat_Challenge06
{
    /**
     * BlueprintGeneratedClass /Game/FX/Baseball/Blueprints/BB_Trail_Normal_Flat_Challenge06.BB_Trail_Normal_Flat_Challenge06_C
     * Size -> 0x0000 (FullSize[0x037C] - InheritedSize[0x037C])
     */
    class ABB_Trail_Normal_Flat_Challenge06_C : public CMN_Trail_Base::ACMN_Trail_Base_C
    {
    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/FX/Baseball/Blueprints/BB_Trail_Normal_Flat_Challenge06.BB_Trail_Normal_Flat_Challenge06_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
