#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FPointerToUberGraphFrame.h"
#include "BP_TrophyAward_TennisBase_ABP_TrophyAward_TennisBase_C.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BP_TrophyAward_Ace
{
    /**
     * BlueprintGeneratedClass /Game/Blueprints/Trophy/TrophyAward/Tennis/BP_TrophyAward_Ace.BP_TrophyAward_Ace_C
     * Size -> 0x000F (FullSize[0x03B8] - InheritedSize[0x03A9])
     */
    class ABP_TrophyAward_Ace_C : public BP_TrophyAward_TennisBase::ABP_TrophyAward_TennisBase_C
    {
    public:
        uint8_t                                                      UnknownData_0000[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::FPointerToUberGraphFrame                             UberGraphFrame;                                          //  ZeroConstructor, Transient, DuplicateTransient

    public:
        void UserConstructionScript();
        void OnAceEvent();
        void ExecuteUbergraph_BP_TrophyAward_Ace(int32_t EntryPoint);
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("BlueprintGeneratedClass /Game/Blueprints/Trophy/TrophyAward/Tennis/BP_TrophyAward_Ace.BP_TrophyAward_Ace_C");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
