#pragma once
#pragma warning(disable: 4267)

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BW_ResultsTracks
{
    // --------------------------------------------------
    // # Classes
    // --------------------------------------------------
    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Initialize_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_UserConstructionScript_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot0__FinishedFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot0__UpdateFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot1__FinishedFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot1__UpdateFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot2__FinishedFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot2__UpdateFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot3__FinishedFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot3__UpdateFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot4__FinishedFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_Timeline_Slot4__UpdateFunc_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_ReceiveBeginPlay_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_DisplaySlot0_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_DisplaySlot1_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_DisplaySlot2_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_DisplaySlot3_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_DisplaySlot4_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ABW_ResultsTracks_C_ExecuteUbergraph_BW_ResultsTracks_Params
    {
    public:
        int32_t                                                      EntryPoint;                                              //  0x0000(0x0004)  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
