#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FRawDistributionFloat.h"
#include "Engine_FRawDistributionVector.h"
#include "BasicTypes_TArray.h"
#include "Engine_UParticleModuleEventReceiverBase.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class UPhysicalMaterial; };
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
    /**
     * Class /Script/Engine.ParticleModuleEventReceiverSpawn
     * Size -> 0x00A8 (FullSize[0x00E8] - InheritedSize[0x0040])
     */
    class UParticleModuleEventReceiverSpawn : public Engine::UParticleModuleEventReceiverBase
    {
    public:
        Engine::FRawDistributionFloat                                SpawnCount;                                              //  Edit, ContainsInstancedReference, NativeAccessSpecifierPublic
        bool                                                         bUseParticleTime : 1;                                    //  BIT_FIELD Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bUsePSysLocation : 1;                                    //  BIT_FIELD Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bInheritVelocity : 1;                                    //  BIT_FIELD Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::FRawDistributionVector                               InheritVelocityScale;                                    //  Edit, ContainsInstancedReference, NativeAccessSpecifierPublic
        BasicTypes::TArray<Engine::UPhysicalMaterial*>               PhysicalMaterials;                                       //  Edit, ZeroConstructor, NativeAccessSpecifierPublic
        bool                                                         bBanPhysicalMaterials : 1;                               //  BIT_FIELD Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0001[0x7];                                   //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/Engine.ParticleModuleEventReceiverSpawn");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
