#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "Engine_FGPUSpriteEmitterInfo.h"
#include "Engine_FGPUSpriteResourceData.h"
#include "Engine_UParticleModuleTypeDataBase.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
    /**
     * Class /Script/Engine.ParticleModuleTypeDataGpu
     * Size -> 0x0430 (FullSize[0x0460] - InheritedSize[0x0030])
     */
    class UParticleModuleTypeDataGpu : public Engine::UParticleModuleTypeDataBase
    {
    public:
        Engine::FGPUSpriteEmitterInfo                                EmitterInfo;                                             //  ContainsInstancedReference, NativeAccessSpecifierPublic
        Engine::FGPUSpriteResourceData                               ResourceData;                                            //  NativeAccessSpecifierPublic
        float                                                        CameraMotionBlurAmount;                                  //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        bool                                                         bClearExistingParticlesOnInit : 1;                       //  BIT_FIELD Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0xB];                                   //  MISSED OFFSET (PADDING)

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/Engine.ParticleModuleTypeDataGpu");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
