#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "CoreUObject_FVector.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
    /**
     * ScriptStruct /Script/Engine.ScaleTrack
     * Size -> 0x0020
     */
    struct FScaleTrack
    {
    public:
        BasicTypes::TArray<CoreUObject::FVector>                     ScaleKeys;                                               //  ZeroConstructor, NativeAccessSpecifierPublic
        BasicTypes::TArray<float>                                    Times;                                                   //  ZeroConstructor, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
