#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_FString.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::EngineMessages
{
    /**
     * ScriptStruct /Script/EngineMessages.EngineServiceNotification
     * Size -> 0x0018
     */
    struct FEngineServiceNotification
    {
    public:
        BasicTypes::FString                                          Text;                                                    //  Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        double                                                       TimeSeconds;                                             //  Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
