#pragma once
#pragma warning(disable: 4267)

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "GameplayTags_FGameplayTagContainer.h"
#include "GameplayTags_FGameplayTag.h"
#include "BasicTypes_FString.h"
#include "GameplayTags_FGameplayTagQuery.h"
#include "BasicTypes_TArray.h"
#include "BasicTypes_TScriptInterface.h"
#include "GameplayTags_IGameplayTagAssetInterface.h"
#include "BasicTypes_FName.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UObject; };
namespace CG::Engine { class AActor; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::GameplayTags
{
    // --------------------------------------------------
    // # Classes
    // --------------------------------------------------
    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_RemoveGameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   Tag;                                                     //  0x0020(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0028(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_NotEqual_TagTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   A;                                                       //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        BasicTypes::FString                                          B;                                                       //  0x0008(0x0010)  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0018(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_NotEqual_TagContainerTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          A;                                                       //  0x0000(0x0020)  (Parm, NativeAccessSpecifierPublic)
        BasicTypes::FString                                          B;                                                       //  0x0020(0x0010)  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0030(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_NotEqual_GameplayTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          A;                                                       //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          B;                                                       //  0x0020(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0040(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_NotEqual_GameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   A;                                                       //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   B;                                                       //  0x0008(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0010(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MatchesTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   TagOne;                                                  //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   TagTwo;                                                  //  0x0008(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         bExactMatch;                                             //  0x0010(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0011(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MatchesAnyTags_Params
    {
    public:
        GameplayTags::FGameplayTag                                   TagOne;                                                  //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          OtherContainer;                                          //  0x0008(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         bExactMatch;                                             //  0x0028(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0029(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MakeLiteralGameplayTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          Value;                                                   //  0x0000(0x0020)  (Parm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          ReturnValue;                                             //  0x0020(0x0020)  (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MakeLiteralGameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   Value;                                                   //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   ReturnValue;                                             //  0x0008(0x0008)  (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MakeGameplayTagQuery_Params
    {
    public:
        GameplayTags::FGameplayTagQuery                              TagQuery;                                                //  0x0000(0x0048)  (Parm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagQuery                              ReturnValue;                                             //  0x0048(0x0048)  (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MakeGameplayTagContainerFromTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   SingleTag;                                               //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          ReturnValue;                                             //  0x0008(0x0020)  (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_MakeGameplayTagContainerFromArray_Params
    {
    public:
        BasicTypes::TArray<GameplayTags::FGameplayTag>               GameplayTags;                                            //  0x0000(0x0010)  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          ReturnValue;                                             //  0x0010(0x0020)  (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_IsGameplayTagValid_Params
    {
    public:
        GameplayTags::FGameplayTag                                   GameplayTag;                                             //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0008(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_HasTag_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   Tag;                                                     //  0x0020(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         bExactMatch;                                             //  0x0028(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0029(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_HasAnyTags_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          OtherContainer;                                          //  0x0020(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         bExactMatch;                                             //  0x0040(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0041(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_HasAllTags_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          OtherContainer;                                          //  0x0020(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         bExactMatch;                                             //  0x0040(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0041(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_HasAllMatchingGameplayTags_Params
    {
    public:
        BasicTypes::TScriptInterface<GameplayTags::IGameplayTagAssetInterface> TagContainerInterface;                                   //  0x0000(0x0010)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          OtherContainer;                                          //  0x0010(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0030(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_GetTagName_Params
    {
    public:
        GameplayTags::FGameplayTag                                   GameplayTag;                                             //  0x0000(0x0008)  (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        BasicTypes::FName                                            ReturnValue;                                             //  0x0008(0x0008)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_GetNumGameplayTagsInContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        int32_t                                                      ReturnValue;                                             //  0x0020(0x0004)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_GetDebugStringFromGameplayTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        BasicTypes::FString                                          ReturnValue;                                             //  0x0020(0x0010)  (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_GetDebugStringFromGameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   GameplayTag;                                             //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        BasicTypes::FString                                          ReturnValue;                                             //  0x0008(0x0010)  (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_GetAllActorsOfClassMatchingTagQuery_Params
    {
    public:
        CoreUObject::UObject*                                        WorldContextObject;                                      //  0x0000(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        Engine::AActor*                                              ActorClass;                                              //  0x0008(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagQuery                              GameplayTagQuery;                                        //  0x0010(0x0048)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        BasicTypes::TArray<Engine::AActor*>                          OutActors;                                               //  0x0058(0x0010)  (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_EqualEqual_GameplayTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          A;                                                       //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          B;                                                       //  0x0020(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0040(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_EqualEqual_GameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   A;                                                       //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   B;                                                       //  0x0008(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0010(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_DoesTagAssetInterfaceHaveTag_Params
    {
    public:
        BasicTypes::TScriptInterface<GameplayTags::IGameplayTagAssetInterface> TagContainerInterface;                                   //  0x0000(0x0010)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   Tag;                                                     //  0x0010(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0018(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_DoesContainerMatchTagQuery_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagQuery                              TagQuery;                                                //  0x0020(0x0048)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0068(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_BreakGameplayTagContainer_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          GameplayTagContainer;                                    //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        BasicTypes::TArray<GameplayTags::FGameplayTag>               GameplayTags;                                            //  0x0020(0x0010)  (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_AppendGameplayTagContainers_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          InOutTagContainer;                                       //  0x0000(0x0020)  (Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTagContainer                          InTagContainer;                                          //  0x0020(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class UBlueprintGameplayTagLibrary_AddGameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        GameplayTags::FGameplayTag                                   Tag;                                                     //  0x0020(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class IGameplayTagAssetInterface_HasMatchingGameplayTag_Params
    {
    public:
        GameplayTags::FGameplayTag                                   TagToCheck;                                              //  0x0000(0x0008)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0008(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class IGameplayTagAssetInterface_HasAnyMatchingGameplayTags_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0020(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class IGameplayTagAssetInterface_HasAllMatchingGameplayTags_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         ReturnValue;                                             //  0x0020(0x0001)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class IGameplayTagAssetInterface_GetOwnedGameplayTags_Params
    {
    public:
        GameplayTags::FGameplayTagContainer                          TagContainer;                                            //  0x0000(0x0020)  (Parm, OutParm, NativeAccessSpecifierPublic)
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
