#pragma once
#pragma warning(disable: 4267)

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "CoreUObject_FSoftClassPath.h"
#include "BasicTypes_TArray.h"
#include "MovieScene_FMovieSceneObjectBindingID.h"
#include "MovieScene_FMovieSceneSequencePlaybackSettings.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::LevelSequence { class ULevelSequence; };
namespace CG::Engine { class AActor; };
namespace CG::CoreUObject { class UObject; };
namespace CG::LevelSequence { class ULevelSequenceBurnInInitSettings; };
namespace CG::LevelSequence { class ALevelSequenceActor; };
namespace CG::LevelSequence { class ULevelSequencePlayer; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::LevelSequence
{
    // --------------------------------------------------
    // # Classes
    // --------------------------------------------------
    /**
     * 
     * Size -> 0x0000
     */
    class ULevelSequenceBurnInOptions_SetBurnIn_Params
    {
    public:
        CoreUObject::FSoftClassPath                                  InBurnInClass;                                           //  0x0000(0x0018)  (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_SetSequence_Params
    {
    public:
        LevelSequence::ULevelSequence*                               InSequence;                                              //  0x0000(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_SetEventReceivers_Params
    {
    public:
        BasicTypes::TArray<Engine::AActor*>                          AdditionalReceivers;                                     //  0x0000(0x0010)  (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_SetBinding_Params
    {
    public:
        MovieScene::FMovieSceneObjectBindingID                       Binding;                                                 //  0x0000(0x0018)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        BasicTypes::TArray<Engine::AActor*>                          Actors;                                                  //  0x0018(0x0010)  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
        bool                                                         bAllowBindingsFromAsset;                                 //  0x0028(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_ResetBindings_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_ResetBinding_Params
    {
    public:
        MovieScene::FMovieSceneObjectBindingID                       Binding;                                                 //  0x0000(0x0018)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_RemoveBinding_Params
    {
    public:
        MovieScene::FMovieSceneObjectBindingID                       Binding;                                                 //  0x0000(0x0018)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        Engine::AActor*                                              Actor;                                                   //  0x0018(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_GetSequence_Params
    {
    public:
        bool                                                         bLoad;                                                   //  0x0000(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         bInitializePlayer;                                       //  0x0001(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        uint8_t                                                      UnknownData_0000[0x6];                                   //  0x0002(0x0006) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY) ()
        LevelSequence::ULevelSequence*                               ReturnValue;                                             //  0x0008(0x0008)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ALevelSequenceActor_AddBinding_Params
    {
    public:
        MovieScene::FMovieSceneObjectBindingID                       Binding;                                                 //  0x0000(0x0018)  (Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        Engine::AActor*                                              Actor;                                                   //  0x0018(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        bool                                                         bAllowBindingsFromAsset;                                 //  0x0020(0x0001)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ULevelSequenceBurnIn_SetSettings_Params
    {
    public:
        CoreUObject::UObject*                                        InSettings;                                              //  0x0000(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ULevelSequenceBurnIn_GetSettingsClass_Params
    {
    public:
        LevelSequence::ULevelSequenceBurnInInitSettings*             ReturnValue;                                             //  0x0000(0x0008)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ULevelSequenceDirector_OnCreated_Params
    {
    };

    /**
     * 
     * Size -> 0x0000
     */
    class ULevelSequencePlayer_CreateLevelSequencePlayer_Params
    {
    public:
        CoreUObject::UObject*                                        WorldContextObject;                                      //  0x0000(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        LevelSequence::ULevelSequence*                               LevelSequence;                                           //  0x0008(0x0008)  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        MovieScene::FMovieSceneSequencePlaybackSettings              Settings;                                                //  0x0010(0x0040)  (Parm, NativeAccessSpecifierPublic)
        LevelSequence::ALevelSequenceActor*                          OutActor;                                                //  0x0050(0x0008)  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
        LevelSequence::ULevelSequencePlayer*                         ReturnValue;                                             //  0x0058(0x0008)  (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
