#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_FText.h"
#include "BasicTypes_FString.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MediaAssets
{
    /**
     * ScriptStruct /Script/MediaAssets.MediaCaptureDevice
     * Size -> 0x0028
     */
    struct FMediaCaptureDevice
    {
    public:
        BasicTypes::FText                                            DisplayName;                                             //  BlueprintVisible, BlueprintReadOnly, Transient, NativeAccessSpecifierPublic
        BasicTypes::FString                                          URL;                                                     //  BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
