#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MeshDescription
{
    // --------------------------------------------------
    // # Enums
    // --------------------------------------------------
    /**
     * Enum /Script/MeshDescription.EComputeNTBsOptions
     */
    enum class EComputeNTBsOptions : uint8_t
    {
        None         = 0,
        Normals      = 1,
        Tangents     = 2,
        WeightedNTBs = 3,
        MAX          = 4
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
