#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MovieSceneTracks
{
    // --------------------------------------------------
    // # Enums
    // --------------------------------------------------
    /**
     * Enum /Script/MovieSceneTracks.MovieScene3DPathSection_Axis
     */
    enum class EMovieScene3DPathSection_Axis : uint8_t
    {
        MovieScene3DPathSection_AxisX                           = 0,
        MovieScene3DPathSection_AxisY                           = 1,
        MovieScene3DPathSection_AxisZ                           = 2,
        MovieScene3DPathSection_AxisNEG_X                       = 3,
        MovieScene3DPathSection_AxisNEG_Y                       = 4,
        MovieScene3DPathSection_AxisNEG_Z                       = 5,
        MovieScene3DPathSection_AxisMovieScene3DPathSection_MAX = 6
    };

    /**
     * Enum /Script/MovieSceneTracks.EFireEventsAtPosition
     */
    enum class EFireEventsAtPosition : uint8_t
    {
        AtStartOfEvaluation = 0,
        AtEndOfEvaluation   = 1,
        AfterSpawn          = 2,
        MAX                 = 3
    };

    /**
     * Enum /Script/MovieSceneTracks.ELevelVisibility
     */
    enum class ELevelVisibility : uint8_t
    {
        Visible = 0,
        Hidden  = 1,
        MAX     = 2
    };

    /**
     * Enum /Script/MovieSceneTracks.EParticleKey
     */
    enum class EParticleKey : uint8_t
    {
        Activate   = 0,
        Deactivate = 1,
        Trigger    = 2,
        MAX        = 3
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
