#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "MovieSceneTracks_FMovieSceneCameraShakeSectionData.h"
#include "CoreUObject_FFrameNumber.h"
#include "MovieSceneTracks_FMovieSceneAdditiveCameraAnimationTemplate.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::MovieSceneTracks
{
    /**
     * ScriptStruct /Script/MovieSceneTracks.MovieSceneCameraShakeSectionTemplate
     * Size -> 0x0028 (FullSize[0x0048] - InheritedSize[0x0020])
     */
    struct FMovieSceneCameraShakeSectionTemplate : public MovieSceneTracks::FMovieSceneAdditiveCameraAnimationTemplate
    {
    public:
        MovieSceneTracks::FMovieSceneCameraShakeSectionData          SourceData;                                              //  NoDestructor, NativeAccessSpecifierPrivate
        CoreUObject::FFrameNumber                                    SectionStartTime;                                        //  NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate
        uint8_t                                                      UnknownData_0000[0x4];                                   //  MISSED OFFSET (PADDING)
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
