#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "SportsScramble_ENUMS.h"
#include "BasicTypes_FText.h"
#include "BasicTypes_FName.h"
#include "PnpGameType_ENUMS.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class AActor; };
namespace CG::Engine { class UTexture2D; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::PnPDefinitionEntry
{
    /**
     * UserDefinedStruct /Game/Datatables/Structs/PnPDefinitionEntry.PnpDefinitionEntry
     * Size -> 0x0069
     */
    struct FPnpDefinitionEntry
    {
    public:
        SportsScramble::EScramSport                                  Sport_2_91C890A94F86972300BB239BC0F160C8;                //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0000[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::AActor*                                              PnPGameClass_21_E1996BE849B3759CFDC40A88588A6C1D;        //  Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FText                                            Title_8_BEFC0FED49F408C0E395AAA079E79F5F;                //  Edit, BlueprintVisible
        BasicTypes::FText                                            Description_10_7FA0F7514C564A6F57B95790A7CE8882;         //  Edit, BlueprintVisible
        int32_t                                                      UnlockOverride_13_F13694EB49BB7C3D934546BD4D6C14C5;      //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0001[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        Engine::UTexture2D*                                          PreviewImage_17_26A2E52A4BA8AFE5BF71D299064327E8;        //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        BasicTypes::FName                                            SpawnLocOverride_24_81A902FB4F0561AE812483AB0C6222B1;    //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        bool                                                         UseStandardArena_26_67CB4B434426C3FFA6D82C8971059239;    //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
        uint8_t                                                      UnknownData_0002[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::FName                                            LevelOverride_29_28D51240433E631649EC3784FED3217E;       //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        PnpGameType::EPnpGameType                                    PnpGameType_33_5EAE034C4A7A2DB12879FBAE7D38D298;         //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
