#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "SlateCore_ENUMS.h"
#include "SlateCore_FSlateBrush.h"
#include "SlateCore_FMargin.h"
#include "SlateCore_FSlateColor.h"
#include "SlateCore_FSlateSound.h"
#include "SlateCore_FSlateWidgetStyle.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::SlateCore
{
    /**
     * ScriptStruct /Script/SlateCore.CheckBoxStyle
     * Size -> 0x0578 (FullSize[0x0580] - InheritedSize[0x0008])
     */
    struct FCheckBoxStyle : public SlateCore::FSlateWidgetStyle
    {
    public:
        SlateCore::ESlateCheckBoxType                                CheckBoxType;                                            //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic
        uint8_t                                                      UnknownData_0000[0x7];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        SlateCore::FSlateBrush                                       UncheckedImage;                                          //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       UncheckedHoveredImage;                                   //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       UncheckedPressedImage;                                   //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       CheckedImage;                                            //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       CheckedHoveredImage;                                     //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       CheckedPressedImage;                                     //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       UndeterminedImage;                                       //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       UndeterminedHoveredImage;                                //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateBrush                                       UndeterminedPressedImage;                                //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FMargin                                           Padding;                                                 //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic
        SlateCore::FSlateColor                                       ForegroundColor;                                         //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateColor                                       BorderBackgroundColor;                                   //  Edit, BlueprintVisible, NativeAccessSpecifierPublic
        SlateCore::FSlateSound                                       CheckedSlateSound;                                       //  Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic
        SlateCore::FSlateSound                                       UncheckedSlateSound;                                     //  Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic
        SlateCore::FSlateSound                                       HoveredSlateSound;                                       //  Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
