#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "SportsScramble_FRunnerAnimInstanceProxy.h"
#include "SportsScramble_UBaseballAIAnimInstance.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::CoreUObject { class UClass; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::SportsScramble
{
    /**
     * Class /Script/SportsScramble.BaseballRunnerAIAnimInstance
     * Size -> 0x0584 (FullSize[0x08E0] - InheritedSize[0x035C])
     */
    class UBaseballRunnerAIAnimInstance : public SportsScramble::UBaseballAIAnimInstance
    {
    public:
        uint8_t                                                      UnknownData_0000[0x4];                                   //  Fix Super Size
        SportsScramble::FRunnerAnimInstanceProxy                     Proxy;                                                   //  BlueprintVisible, Transient, NativeAccessSpecifierPrivate

    public:
        static inline CoreUObject::UClass* StaticClass()
        {
            static CoreUObject::UClass* ptr = nullptr;
            if (!ptr)
                ptr = CoreUObject::UObject::FindClass("Class /Script/SportsScramble.BaseballRunnerAIAnimInstance");
            return ptr;
        }
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
