#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>
#include "BasicTypes_TArray.h"
#include "ScramblerTargetSet_FScramblerTargetSet.h"

// --------------------------------------------------
// # Forwards
// --------------------------------------------------
namespace CG::Engine { class AActor; };

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::TennisScrambleScheduleEntry
{
    /**
     * UserDefinedStruct /Game/Datatables/Structs/TennisScrambleScheduleEntry.TennisScrambleScheduleEntry
     * Size -> 0x0070
     */
    struct FTennisScrambleScheduleEntry
    {
    public:
        int32_t                                                      Point_2_606524BB46E481C9BC8347BAA8EB9FA0;                //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      InitialTargetCount_10_962F8DBA4A2057A83EFCF586B17CBC98;  //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      MaxTargetCount_12_17D80791417BCA78B246D684789FD47F;      //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0000[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::TArray<ScramblerTargetSet::FScramblerTargetSet>  ScrambleSetInitial_26_70766DF74271363BF67D4AB086BDC0C6;  //  Edit, BlueprintVisible, ZeroConstructor
        BasicTypes::TArray<ScramblerTargetSet::FScramblerTargetSet>  ScrambleSetReinforcements_30_DFB642D0449B679DF869AF80B539008A; //  Edit, BlueprintVisible, ZeroConstructor
        float                                                        ReinforcementDelay_16_C5E783894E849A09F55B9EB15869F217;  //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      ReinforcementCountMin_33_BEE37EE74573AA5ADBEBEDB49041AC74; //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        int32_t                                                      ReinforcementCountMax_34_F94954904F22012C13A335A41B9B846F; //  Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash
        uint8_t                                                      UnknownData_0001[0x4];                                   //  MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
        BasicTypes::TArray<int32_t>                                  SpawnLocationsOverrideInitial_35_856434B0465155DAEA75A8B40D4899EB; //  Edit, BlueprintVisible, ZeroConstructor
        BasicTypes::TArray<int32_t>                                  SpawnLocationsOverrideReinforcements_38_16F05BDA4E8D06943456EBB303EADF22; //  Edit, BlueprintVisible, ZeroConstructor
        BasicTypes::TArray<Engine::AActor*>                          DisabledClasses_42_1FA4B6994B461E6C229A6CB0D224F349;     //  Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate
    };
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
