#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include <cstdint>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::TN_ShotDirection
{
    // --------------------------------------------------
    // # Enums
    // --------------------------------------------------
    /**
     * UserDefinedEnum /Game/Datatables/Enums/TN_ShotDirection.TN_ShotDirection
     */
    enum class ETN_ShotDirection : uint8_t
    {
        TN_ShotDirectionNewEnumerator0 = 0,
        TN_ShotDirectionNewEnumerator1 = 1,
        TN_ShotDirectionNewEnumerator2 = 2,
        TN_ShotDirectionNewEnumerator3 = 3,
        TN_ShotDirectionNewEnumerator4 = 4,
        TN_ShotDirectionTN_MAX         = 5
    };

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
