/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include "../pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/BaseballAIPitcher_TrainingNoImbued_Blueprint_PARAMS.h"
#include "Headers/BaseballAIPitcher_TrainingNoImbued_Blueprint_ABaseballAIPitcher_TrainingNoImbued_Blueprint_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BaseballAIPitcher_TrainingNoImbued_Blueprint
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.UserConstructionScript
     *         Flags  -> (Event, Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::UserConstructionScript()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.UserConstructionScript");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_UserConstructionScript_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineSpawnIn__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::TimelineSpawnIn__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineSpawnIn__FinishedFunc");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_TimelineSpawnIn__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineSpawnIn__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::TimelineSpawnIn__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineSpawnIn__UpdateFunc");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_TimelineSpawnIn__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineDespawn__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::TimelineDespawn__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineDespawn__FinishedFunc");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_TimelineDespawn__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineDespawn__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::TimelineDespawn__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.TimelineDespawn__UpdateFunc");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_TimelineDespawn__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ReceiveBeginPlay
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::ReceiveBeginPlay()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ReceiveBeginPlay");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_ReceiveBeginPlay_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ReceiveEndPlay
     *         Flags  -> (Event, Public, BlueprintEvent)
     * Parameters:
     *         Engine::EEndPlayReason                             EndPlayReason                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::ReceiveEndPlay(Engine::EEndPlayReason EndPlayReason)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ReceiveEndPlay");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_ReceiveEndPlay_Params params {};
        params.EndPlayReason = EndPlayReason;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.DespawnPitcher
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::DespawnPitcher()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.DespawnPitcher");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_DespawnPitcher_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ExecuteUbergraph_BaseballAIPitcher_TrainingNoImbued_Blueprint
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void ABaseballAIPitcher_TrainingNoImbued_Blueprint_C::ExecuteUbergraph_BaseballAIPitcher_TrainingNoImbued_Blueprint(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/AI/Baseball/BaseballAIPitcher_TrainingNoImbued_Blueprint.BaseballAIPitcher_TrainingNoImbued_Blueprint_C.ExecuteUbergraph_BaseballAIPitcher_TrainingNoImbued_Blueprint");
        
        ABaseballAIPitcher_TrainingNoImbued_Blueprint_C_ExecuteUbergraph_BaseballAIPitcher_TrainingNoImbued_Blueprint_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
