/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/BB_Scoreboard_Training_Widget_PARAMS.h"
#include "Headers/BB_Scoreboard_Training_Widget_UBB_Scoreboard_Training_Widget_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::BB_Scoreboard_Training_Widget
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Baseball/BB_Scoreboard_Training_Widget.BB_Scoreboard_Training_Widget_C.Construct
     *         Flags  -> (BlueprintCosmetic, Event, Public, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void UBB_Scoreboard_Training_Widget_C::Construct()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Baseball/BB_Scoreboard_Training_Widget.BB_Scoreboard_Training_Widget_C.Construct");
        
        UBB_Scoreboard_Training_Widget_C_Construct_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Baseball/BB_Scoreboard_Training_Widget.BB_Scoreboard_Training_Widget_C.ExecuteUbergraph_BB_Scoreboard_Training_Widget
     *         Flags  -> (Final)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void UBB_Scoreboard_Training_Widget_C::ExecuteUbergraph_BB_Scoreboard_Training_Widget(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Baseball/BB_Scoreboard_Training_Widget.BB_Scoreboard_Training_Widget_C.ExecuteUbergraph_BB_Scoreboard_Training_Widget");
        
        UBB_Scoreboard_Training_Widget_C_ExecuteUbergraph_BB_Scoreboard_Training_Widget_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
