/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    10/14/2024                  |
 * ----------------------------------------
 */

#include "pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/Menu_ResultsScore_PARAMS.h"
#include "Headers/Menu_ResultsScore_AMenu_ResultsScore_C.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Menu_ResultsScore
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------
    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.EnableMenuInput
     *         Flags  -> (Public, HasOutParms, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               InputEnabled                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::EnableMenuInput(bool* InputEnabled)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.EnableMenuInput");
        
        AMenu_ResultsScore_C_EnableMenuInput_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (InputEnabled != nullptr)
            *InputEnabled = params.InputEnabled;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.DisableMenuInput
     *         Flags  -> (Public, HasOutParms, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               InputDisabled                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::DisableMenuInput(bool* InputDisabled)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.DisableMenuInput");
        
        AMenu_ResultsScore_C_DisableMenuInput_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (InputDisabled != nullptr)
            *InputDisabled = params.InputDisabled;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RemoveSubMenu
     *         Flags  -> (Public, HasOutParms, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               Removed                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::RemoveSubMenu(bool* Removed)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RemoveSubMenu");
        
        AMenu_ResultsScore_C_RemoveSubMenu_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (Removed != nullptr)
            *Removed = params.Removed;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.HideSubMenu
     *         Flags  -> (Public, HasOutParms, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               MenuHidden                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::HideSubMenu(bool* MenuHidden)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.HideSubMenu");
        
        AMenu_ResultsScore_C_HideSubMenu_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (MenuHidden != nullptr)
            *MenuHidden = params.MenuHidden;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RestoreSubMenu
     *         Flags  -> (Public, HasOutParms, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         bool                                               MenuShown                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::RestoreSubMenu(bool* MenuShown)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RestoreSubMenu");
        
        AMenu_ResultsScore_C_RestoreSubMenu_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
        
        if (MenuShown != nullptr)
            *MenuShown = params.MenuShown;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Initialize
     *         Flags  -> (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Initialize()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Initialize");
        
        AMenu_ResultsScore_C_Initialize_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.UserConstructionScript
     *         Flags  -> (Event, Public, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::UserConstructionScript()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.UserConstructionScript");
        
        AMenu_ResultsScore_C_UserConstructionScript_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleText__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ScaleText__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleText__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_ScaleText__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleText__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ScaleText__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleText__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_ScaleText__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleBox__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ScaleBox__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleBox__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_ScaleBox__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleBox__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ScaleBox__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ScaleBox__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_ScaleBox__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_SwapBoxText__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_SwapBoxText__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_SwapBoxText__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_SwapBoxText__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_SwapBoxText__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_SwapBoxText__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_SwapBoxText__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_SwapBoxText__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowHighScore__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ShowHighScore__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowHighScore__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_ShowHighScore__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowHighScore__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ShowHighScore__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowHighScore__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_ShowHighScore__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowMessage__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ShowMessage__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowMessage__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_ShowMessage__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowMessage__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_ShowMessage__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_ShowMessage__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_ShowMessage__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_MoveInnerMessage__FinishedFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_MoveInnerMessage__FinishedFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_MoveInnerMessage__FinishedFunc");
        
        AMenu_ResultsScore_C_Timeline_MoveInnerMessage__FinishedFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_MoveInnerMessage__UpdateFunc
     *         Flags  -> (BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::Timeline_MoveInnerMessage__UpdateFunc()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.Timeline_MoveInnerMessage__UpdateFunc");
        
        AMenu_ResultsScore_C_Timeline_MoveInnerMessage__UpdateFunc_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveBeginPlay
     *         Flags  -> (Event, Protected, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ReceiveBeginPlay()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveBeginPlay");
        
        AMenu_ResultsScore_C_ReceiveBeginPlay_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveTick
     *         Flags  -> (Event, Public, BlueprintEvent)
     * Parameters:
     *         float                                              DeltaSeconds                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ReceiveTick(float DeltaSeconds)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveTick");
        
        AMenu_ResultsScore_C_ReceiveTick_Params params {};
        params.DeltaSeconds = DeltaSeconds;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveEndPlay
     *         Flags  -> (Event, Public, BlueprintEvent)
     * Parameters:
     *         Engine::EEndPlayReason                             EndPlayReason                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ReceiveEndPlay(Engine::EEndPlayReason EndPlayReason)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ReceiveEndPlay");
        
        AMenu_ResultsScore_C_ReceiveEndPlay_Params params {};
        params.EndPlayReason = EndPlayReason;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RevealMessage
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::RevealMessage()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RevealMessage");
        
        AMenu_ResultsScore_C_RevealMessage_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RevealScoreBox
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::RevealScoreBox()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.RevealScoreBox");
        
        AMenu_ResultsScore_C_RevealScoreBox_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowScore
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ShowScore()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowScore");
        
        AMenu_ResultsScore_C_ShowScore_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowHighScore
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ShowHighScore()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowHighScore");
        
        AMenu_ResultsScore_C_ShowHighScore_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.MoveMessage
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::MoveMessage()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.MoveMessage");
        
        AMenu_ResultsScore_C_MoveMessage_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowInnerMessage
     *         Flags  -> (BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ShowInnerMessage()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ShowInnerMessage");
        
        AMenu_ResultsScore_C_ShowInnerMessage_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ExecuteUbergraph_Menu_ResultsScore
     *         Flags  -> (Final, HasDefaults)
     * Parameters:
     *         int32_t                                            EntryPoint                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ExecuteUbergraph_Menu_ResultsScore(int32_t EntryPoint)
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ExecuteUbergraph_Menu_ResultsScore");
        
        AMenu_ResultsScore_C_ExecuteUbergraph_Menu_ResultsScore_Params params {};
        params.EntryPoint = EntryPoint;
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

    /**
     * Function:
     *         RVA    -> 0x006628B0
     *         Name   -> Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ResultsScoreComplete__DelegateSignature
     *         Flags  -> (Public, Delegate, BlueprintCallable, BlueprintEvent)
     * Parameters:
     *         void                                               ReturnValue
     */
    void AMenu_ResultsScore_C::ResultsScoreComplete__DelegateSignature()
    {
        static CoreUObject::UFunction* fn = nullptr;
        if (!fn)
            fn = CoreUObject::UObject::FindObject<CoreUObject::UFunction>("Function /Game/Blueprints/UI/Frontend/SubMenus/Menu_ResultsScore.Menu_ResultsScore_C.ResultsScoreComplete__DelegateSignature");
        
        AMenu_ResultsScore_C_ResultsScoreComplete__DelegateSignature_Params params {};
        
        auto flags = fn->FunctionFlags;
        CoreUObject::UObject::ProcessEvent(fn, &params);
        fn->FunctionFlags = flags;
    }

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
