/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    SportsScramble              |
 * | Version: 1                           |
 * | Date:    09/09/2024                  |
 * ----------------------------------------
 */

#include "../pch.h"
#include <cstdint>
#include <vector>
#include <string>
#include <locale>
#include <unordered_set>
#include "Headers/Global_DEFINES.h"
#include "Headers/BasicTypes.h"
#include "Headers/CoreUObject_UFunction.h"
#include "Headers/Slate_ENUMS.h"
#include "Headers/Slate_UButtonWidgetStyle.h"
#include "Headers/Slate_UCheckBoxWidgetStyle.h"
#include "Headers/Slate_UComboBoxWidgetStyle.h"
#include "Headers/Slate_UComboButtonWidgetStyle.h"
#include "Headers/Slate_UEditableTextBoxWidgetStyle.h"
#include "Headers/Slate_UEditableTextWidgetStyle.h"
#include "Headers/Slate_UProgressWidgetStyle.h"
#include "Headers/Slate_UScrollBarWidgetStyle.h"
#include "Headers/Slate_UScrollBoxWidgetStyle.h"
#include "Headers/Slate_USlateSettings.h"
#include "Headers/Slate_USpinBoxWidgetStyle.h"
#include "Headers/Slate_UTextBlockWidgetStyle.h"

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Slate
{
    // --------------------------------------------------
    // # Structs functions
    // --------------------------------------------------

}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
